os: linux
dist: xenial
language: python

branches:
  only:
  - master

jobs:
  fast_finish: true
  allow_failures:
    - python: "pypy3.5"

  include:
    - { python: "2.7", env: TOXENV=py27 }
    - { python: "3.5", env: TOXENV=py35 }
    - { python: "3.6", env: TOXENV=py36 }
    - { python: "3.7", env: TOXENV=py37 }
    - { python: "3.8", env: TOXENV=py38 }
    - { python: "pypy3.5", env: TOXENV=pypy }

    - os: osx
      language: generic
      env: TOXENV=py27,py37

    - python: "3.8"
      env: TOXENV="dist"
      script:
        - python setup.py bdist_wheel
        - tox --installpkg ./dist/tox_venv-*.whl
        - tox  # test sdist

    - python: "3.8"
      env: TOXENV="isort,lint"
      script: tox


# We don't need to get the latest version of Python 3 on macOS. While it
# would be nice, the 5-10 minutes it takes to update Homebrew and upgrade
# the various dependent packages, means that it's is not worth it.
# Note that we also print the python version in case of macOS updates
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python3 --version;
      python3 -m venv venv;
      source venv/bin/activate;
    fi
install:
  - pip install -U six setuptools wheel
  - pip install -U tox
script: tox
after_success:
  - pip install codecov && codecov
  - coverage report
