build: false  # Not a C# project

environment:
  matrix:
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36

matrix:
  fast_finish: true

install:
  - C:\Python36\python -m pip install -U six setuptools wheel
  - C:\Python36\python -m pip install -U tox tox-travis
  - C:\Python36\python setup.py bdist_wheel

test_script:
  - C:\Python36\scripts\tox

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
